name: test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: create test file
        run: echo "test" >test.txt
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: test.txt
          token: ${{ secrets.TOKEN }}
        
